spring:
  application:
    name: ${APPLICATION_NAME}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  datasource:
    url: ${DATASOURCE_URL_LOCAL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: ${DATASOURCE_DRIVER}
  liquibase:
    enabled: true
    change-log: classpath:${CHANGELOG_BASE}/${CHANGELOG_FILE_NAME}

eureka:
  client:
    service-url:
      defaultZone: http://${DEV_IP_ADDRESS}:${EUREKA_PORT}/eureka
  instance:
    prefer-ip-address: true

server:
  port: ${SERVER_PORT}